### ISSUE TITLE
0.6.0 NPM release?

### ISSUE THREAD

**Issue by malept** [endlessm/electron-installer-flatpak#11]
I'm currently updating dependencies for [Electron Forge](https://github.com/electron-userland/electron-forge) and noticed there was a 0.6.0 version committed to git, but not to NPM.

Also, it would be good if there were git tags to more easily look at differences between versions, and/or a NEWS file.

**Comment by nedrichards** [comment]
@wgreenberg I believe you were going to be [looking at this](https://www.npmjs.com/package/electron-installer-flatpak)?

**Comment by wgreenberg** [comment]
hey @malept, v0.6.0 is now published on npm. Sorry about the delay!

**Comment by malept** [comment]
Thanks!
