### ISSUE TITLE
Can't build flatpak on Linux x64

### ISSUE THREAD

**Issue by fmarzocca** [endlessm/electron-installer-flatpak#14]
**What version of `electron-installer-flatpak` are you using?**
**0.6.0**

**What version of `node` and `npm` are you using?**
**4.2.6   3.5.2**
**What operating system are you using?**
**Linux Mint 18.1**

**What actually happened?**
[npm-debug.log](https://github.com/endlessm/electron-installer-flatpak/files/1506858/npm-debug.log)

The application has been built with electron packager and it runs fine in its tree. I have also built a debian package with electron-installer-debian, but I can't get a flatpak...

**Comment by ptomato** [comment]
Thanks for taking the time to report the problem. Can you point me to where I can find MeteoSurf so that I can debug it a bit more? Unfortunately the debug log isn't giving me too much information.

**Comment by fmarzocca** [comment]
The desktop app is not in distribution, still on development (this ticket is one of the problems).
The webapp (only for mobile devices) is here: http://bit.ly/meteo-surf
The description web page is: http://marzocca.net/linux/meteosurf_en.html
(but I'm sure you don't need those)...

The electron app itself is very trivial, an edited version of the "getting-started" app.

Thanks

**Comment by ptomato** [comment]
Maybe you could post the trivial electron app in a gist?

**Comment by fmarzocca** [comment]
doesn't matter. Thank you anyway.

**Comment by fmarzocca** [comment]
here it is:
https://gist.github.com/fmarzocca/a9412fea3b62cf0b2c9587afb3e19ce3

**Comment by ptomato** [comment]
If you can run it again with `DEBUG=flatpak-bundler npm run linux-flatpak` that would provide more information. Looking at what flatpak-bundler does internally, it may be that the `org.freedesktop.Platform` and `org.freedesktop.Sdk` runtimes aren't installed on your system. Flatpak-bundler should install them automatically, but a workaround could be to install them manually before you start.

**Comment by fmarzocca** [comment]
This is the new log
[npm-debug.log](https://github.com/endlessm/electron-installer-flatpak/files/1512933/npm-debug.log)

**Comment by fmarzocca** [comment]
this was the full stdout of the command:
https://gist.github.com/fmarzocca/3a1dfdd8fd2411965519659a04f14e7e

**Comment by ptomato** [comment]
Thanks. The stdout showed what might be the problem. Do you actually have the `flatpak` command line tool installed on your system and available in your `PATH`? The same error happens to me if the tool can't be found.

**Comment by fmarzocca** [comment]
No, I just installed the flatpak module with npm: 

`npm install -g electron-installer-flatpak`

... What else?

**Comment by ptomato** [comment]
You need flatpak support on your system. According to https://flatpak.org/getting.html "Flatpak support is built into Linux Mint 18.3 and newer." I see you have 18.1, so the PPA in [these instructions](https://forums.linuxmint.com/viewtopic.php?t=229637) might help you?

**Comment by fmarzocca** [comment]
I will upgrade to 18.3 and let you know.

Thanks!

**Comment by ptomato** [comment]
OK, thanks! Feel free to reopen this or file another issue if you still have problems after upgrading.
