### ISSUE TITLE
Any plans for FreeBSD?

### ISSUE THREAD

**Issue by Ezerbeth** [endlessm/electron-installer-flatpak#23]
Trying to install this as a dependency for yakyak, and it errors as:

`npm ERR! notsup Unsupported platform for electron-installer-flatpak@0.8.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
`
Any plans to make this work for FreeBSD?

Thank you

**Comment by nedrichards** [comment]
Flatpak itself doesn't work on FreeBSD. It's highly specific to the way Linux makes containers and I suspect it wouldn't be an easy port.
