### ISSUE TITLE
flatpak-bundler ensureSdk() broken

### ISSUE THREAD

**Issue by fatmalama** [endlessm/electron-installer-flatpak#26]
**What version of `electron-installer-flatpak` are you using?**
0.8.0

ensureSdk() of flatpak-bundler is broken, as there's no sdk-version field to be used (it's runtime-version, as the sdk is the devel package for that runtime)
so instead of
`return ensrueRef(options, manifest['sdk-flatpakref'],
    manifest['sdk'], manifest['sdk-version'])`
it should be
`return ensrueRef(options, manifest['sdk-flatpakref'],
    manifest['sdk'], manifest['runtime-version'])`

as flatpak-bundler hasn't been updated since 2017, I thought it would be better to report here

**Comment by ptomato** [comment]
Thanks for the report, it makes sense! Would you like to make a pull request to flatpak-bundler and tag me for review?

**Comment by fatmalama** [comment]
heh, [you already had fixed it](https://github.com/endlessm/flatpak-bundler/commit/2c1970342ad3f95d85f658a414c4c34b24be00b5)

the problem actually is that you didn't publish 0.1.4 to npm. I filed a bug over at endlessm/flatpak-bundler

**Comment by ptomato** [comment]
Oh, okay, thanks :smile:
